---
title: "Experiment 2"
author: "Carolyn Ritchey"
date: "06/15/2022"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")    
library("furniture")
library("psych")
library("corrplot")    
library("nortest")
library("lmerTest")
library("lme4")
library("optimx")  
library("Hmisc")
library("lsmeans")
library("effects")
library("readxl")
library("optimx")
library("gdata") #for interleave
library("ggplot2")
library("dplyr")
library("MuMIn")

#import data
TimeSpent_LogRatio<-read.csv("/Users/cmr0112/Desktop/ToshiAnalysis-Exp2.csv")
TimeSpent_LogRatio$ID <- as.factor(TimeSpent_LogRatio$ID)
TimeSpent_LogRatio$Condition <- as.factor(TimeSpent_LogRatio$Condition)
TimeSpent_LogRatio$Phase <- as.factor(TimeSpent_LogRatio$Phase)
```

```{r Data_Inspection}

#Condition means + standard error
TimeSpent_LogRatio %>%
  group_by(Condition, Phase) %>%
  dplyr::summarize(rawMeans = mean(Data),
                   se   = sd(Data)/sqrt(n())) %>%
  ggplot(aes(x = Phase, y = rawMeans, color=Condition)) +
  geom_line() +
  geom_errorbar(aes(ymin = rawMeans - se, ymax = rawMeans + se))+
  theme_bw()

```

```{r }

# TimeSpent_LogRatio_Empty <- lmer(Data ~ 1 + (1 | ID), 
#                    data = TimeSpent_LogRatio, 
#                    REML = FALSE)
# 
# summary(TimeSpent_LogRatio_Empty)
# 
# #variances
# VarCorr(TimeSpent_LogRatio_Empty)
# 
# ICC_TimeSpent_LogRatio<-0.00000 /(0.00000 +0.43509)
# ICC_TimeSpent_LogRatio

```

```{r RE_Structure}

e2RE.0 = lmer(Data ~ Phase * Condition + (1 | ID),
                  data = TimeSpent_LogRatio,
                  REML = TRUE,
                  control = lmerControl(optimizer = "optimx",
                  calc.derivs = FALSE,
                  optCtrl = list(method = "nlminb",
                  starttests = FALSE,
                  kkt = FALSE)))

e2RE.1 = lmer(Data ~ Phase * Condition + (Phase | ID),
                  data = TimeSpent_LogRatio,
                  REML = TRUE,
                  control = lmerControl(optimizer = "optimx",
                  calc.derivs = FALSE,
                  optCtrl = list(method = "nlminb",
                  starttests = FALSE,
                  kkt = FALSE)))

e2RE.2 = lmer(Data ~ Phase * Condition + (Phase + Condition | ID),
                  data = TimeSpent_LogRatio,
                  REML = TRUE,
                  control = lmerControl(optimizer = "optimx",
                  calc.derivs = FALSE,
                  optCtrl = list(method = "nlminb",
                  starttests = FALSE,
                  kkt = FALSE)))

MuMIn::AICc(e2RE.0,
    e2RE.1, e2RE.2)
 
	
#         df  AICc
# e2RE.0	17	-113.99409		
# e2RE.1	22	-110.48111		
# e2RE.2	44	-46.20241	

#going with e2RE.0

```

```{r Fixed_Effects_Target}

car::Anova(e2RE.0)

# Response: Data
#                   Chisq Df Pr(>Chisq)    
# Phase           184.772  2  < 2.2e-16 ***
# Condition        52.222  4  1.239e-10 ***
# Phase:Condition  87.460  8  1.523e-15 ***

```

```{r Residuals_Target}

#Checking residuals
TimeSpent_LogRatio$pred = predict(e2RE.0)
TimeSpent_LogRatio$resid = resid(e2RE.0)

TimeSpent_LogRatioP1<-filter(TimeSpent_LogRatio,Phase=="B1")
by(TimeSpent_LogRatioP1$resid,TimeSpent_LogRatioP1$Condition,hist)

TimeSpent_LogRatioP2<-filter(TimeSpent_LogRatio,Phase=="A2")
by(TimeSpent_LogRatioP2$resid,TimeSpent_LogRatioP2$Condition,hist)

TimeSpent_LogRatioP3<-filter(TimeSpent_LogRatio,Phase=="C3")
by(TimeSpent_LogRatioP3$resid,TimeSpent_LogRatioP3$Condition,hist)

```

```{r Model_Predictions}

TimeSpent_LogRatio %>%
  group_by(Condition, Phase) %>%
  dplyr::summarize(predMean = mean(pred),
                   se   = sd(pred)/sqrt(n())) %>%
  ggplot(aes(x = Phase, y = predMean, color=Condition)) +
  geom_line() +
  geom_errorbar(aes(ymin = predMean - se, ymax = predMean + se))+
  theme_bw()

write.csv(TimeSpent_LogRatio,"/Users/cmr0112/Desktop/e2_Pred.csv")

```

```{r Specific_Comparisons_Target}

#...looking @ last bin in Phase 1,2; first bin Phase 3 -- all coded '0'

emmeans::emmeans(e2RE.0, pairwise~Condition|Phase, adjust="Holm",at = list(Bin = c(0)))

# $emmeans
# Phase = A2:
#  Condition                           emmean     SE  df lower.CL upper.CL
#  Absent-Absent                     -0.03238 0.0356 103  -0.1029   0.0382
#  Chasing vs. Flipped                0.29820 0.0356 103   0.2276   0.3688
#  Chasing vs. Independent            0.15062 0.0356 103   0.0801   0.2212
#  Chasing vs. Leaving                0.48668 0.0356 103   0.4161   0.5572
#  Chasing vs. Leaving (Replication)  0.38842 0.0356 103   0.3179   0.4590
# 
# Phase = B1:
#  Condition                           emmean     SE  df lower.CL upper.CL
#  Absent-Absent                     -0.00454 0.0356 103  -0.0751   0.0660
#  Chasing vs. Flipped                0.01088 0.0356 103  -0.0597   0.0814
#  Chasing vs. Independent           -0.02512 0.0356 103  -0.0957   0.0454
#  Chasing vs. Leaving                0.00574 0.0356 103  -0.0648   0.0763
#  Chasing vs. Leaving (Replication)  0.03680 0.0356 103  -0.0338   0.1073
# 
# Phase = C3:
#  Condition                           emmean     SE  df lower.CL upper.CL
#  Absent-Absent                     -0.02146 0.0356 103  -0.0920   0.0491
#  Chasing vs. Flipped               -0.00388 0.0356 103  -0.0744   0.0667
#  Chasing vs. Independent            0.01556 0.0356 103  -0.0550   0.0861
#  Chasing vs. Leaving               -0.00856 0.0356 103  -0.0791   0.0620
#  Chasing vs. Leaving (Replication) -0.01481 0.0356 103  -0.0854   0.0557
# 
# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 
# 
# $contrasts
# Phase = A2:
#  contrast                                                    estimate     SE df t.ratio p.value
#  (Absent-Absent) - Chasing vs. Flipped                       -0.33058 0.0493 98  -6.708 <.0001 
#  (Absent-Absent) - Chasing vs. Independent                   -0.18299 0.0493 98  -3.713 0.0014 
#  (Absent-Absent) - Chasing vs. Leaving                       -0.51906 0.0493 98 -10.533 <.0001 
#  (Absent-Absent) - Chasing vs. Leaving (Replication)         -0.42079 0.0493 98  -8.539 <.0001 
#  Chasing vs. Flipped - Chasing vs. Independent                0.14759 0.0493 98   2.995 0.0104 
#  Chasing vs. Flipped - Chasing vs. Leaving                   -0.18848 0.0493 98  -3.825 0.0012 
#  Chasing vs. Flipped - Chasing vs. Leaving (Replication)     -0.09021 0.0493 98  -1.831 0.0978 
#  Chasing vs. Independent - Chasing vs. Leaving               -0.33607 0.0493 98  -6.820 <.0001 
#  Chasing vs. Independent - Chasing vs. Leaving (Replication) -0.23780 0.0493 98  -4.826 <.0001 
#  Chasing vs. Leaving - Chasing vs. Leaving (Replication)      0.09827 0.0493 98   1.994 0.0978 
# 
# Phase = B1:
#  contrast                                                    estimate     SE df t.ratio p.value
#  (Absent-Absent) - Chasing vs. Flipped                       -0.01543 0.0493 98  -0.313 1.0000 
#  (Absent-Absent) - Chasing vs. Independent                    0.02057 0.0493 98   0.417 1.0000 
#  (Absent-Absent) - Chasing vs. Leaving                       -0.01028 0.0493 98  -0.209 1.0000 
#  (Absent-Absent) - Chasing vs. Leaving (Replication)         -0.04134 0.0493 98  -0.839 1.0000 
#  Chasing vs. Flipped - Chasing vs. Independent                0.03600 0.0493 98   0.731 1.0000 
#  Chasing vs. Flipped - Chasing vs. Leaving                    0.00515 0.0493 98   0.104 1.0000 
#  Chasing vs. Flipped - Chasing vs. Leaving (Replication)     -0.02591 0.0493 98  -0.526 1.0000 
#  Chasing vs. Independent - Chasing vs. Leaving               -0.03085 0.0493 98  -0.626 1.0000 
#  Chasing vs. Independent - Chasing vs. Leaving (Replication) -0.06191 0.0493 98  -1.256 1.0000 
#  Chasing vs. Leaving - Chasing vs. Leaving (Replication)     -0.03106 0.0493 98  -0.630 1.0000 
# 
# Phase = C3:
#  contrast                                                    estimate     SE df t.ratio p.value
#  (Absent-Absent) - Chasing vs. Flipped                       -0.01758 0.0493 98  -0.357 1.0000 
#  (Absent-Absent) - Chasing vs. Independent                   -0.03702 0.0493 98  -0.751 1.0000 
#  (Absent-Absent) - Chasing vs. Leaving                       -0.01290 0.0493 98  -0.262 1.0000 
#  (Absent-Absent) - Chasing vs. Leaving (Replication)         -0.00665 0.0493 98  -0.135 1.0000 
#  Chasing vs. Flipped - Chasing vs. Independent               -0.01944 0.0493 98  -0.394 1.0000 
#  Chasing vs. Flipped - Chasing vs. Leaving                    0.00468 0.0493 98   0.095 1.0000 
#  Chasing vs. Flipped - Chasing vs. Leaving (Replication)      0.01093 0.0493 98   0.222 1.0000 
#  Chasing vs. Independent - Chasing vs. Leaving                0.02412 0.0493 98   0.489 1.0000 
#  Chasing vs. Independent - Chasing vs. Leaving (Replication)  0.03037 0.0493 98   0.616 1.0000 
#  Chasing vs. Leaving - Chasing vs. Leaving (Replication)      0.00625 0.0493 98   0.127 1.0000 


emmeans::emmeans(e2RE.0, pairwise~Phase|Condition,adjust="Holm",at = list(Bin = c(0)))

# $emmeans
# Condition = Absent-Absent:
#  Phase   emmean     SE  df lower.CL upper.CL
#  A2    -0.03238 0.0356 103  -0.1029   0.0382
#  B1    -0.00454 0.0356 103  -0.0751   0.0660
#  C3    -0.02146 0.0356 103  -0.0920   0.0491
# 
# Condition = Chasing vs. Flipped:
#  Phase   emmean     SE  df lower.CL upper.CL
#  A2     0.29820 0.0356 103   0.2276   0.3688
#  B1     0.01088 0.0356 103  -0.0597   0.0814
#  C3    -0.00388 0.0356 103  -0.0744   0.0667
# 
# Condition = Chasing vs. Independent:
#  Phase   emmean     SE  df lower.CL upper.CL
#  A2     0.15062 0.0356 103   0.0801   0.2212
#  B1    -0.02512 0.0356 103  -0.0957   0.0454
#  C3     0.01556 0.0356 103  -0.0550   0.0861
# 
# Condition = Chasing vs. Leaving:
#  Phase   emmean     SE  df lower.CL upper.CL
#  A2     0.48668 0.0356 103   0.4161   0.5572
#  B1     0.00574 0.0356 103  -0.0648   0.0763
#  C3    -0.00856 0.0356 103  -0.0791   0.0620
# 
# Condition = Chasing vs. Leaving (Replication):
#  Phase   emmean     SE  df lower.CL upper.CL
#  A2     0.38842 0.0356 103   0.3179   0.4590
#  B1     0.03680 0.0356 103  -0.0338   0.1073
#  C3    -0.01481 0.0356 103  -0.0854   0.0557
# 
# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 
# 
# $contrasts
# Condition = Absent-Absent:
#  contrast estimate     SE df t.ratio p.value
#  A2 - B1   -0.0278 0.0493 98 -0.565  1.0000 
#  A2 - C3   -0.0109 0.0493 98 -0.222  1.0000 
#  B1 - C3    0.0169 0.0493 98  0.343  1.0000 
# 
# Condition = Chasing vs. Flipped:
#  contrast estimate     SE df t.ratio p.value
#  A2 - B1    0.2873 0.0493 98  5.830  <.0001 
#  A2 - C3    0.3021 0.0493 98  6.130  <.0001 
#  B1 - C3    0.0148 0.0493 98  0.300  0.7652 
# 
# Condition = Chasing vs. Independent:
#  contrast estimate     SE df t.ratio p.value
#  A2 - B1    0.1757 0.0493 98  3.566  0.0017 
#  A2 - C3    0.1351 0.0493 98  2.741  0.0146 
#  B1 - C3   -0.0407 0.0493 98 -0.825  0.4111 
# 
# Condition = Chasing vs. Leaving:
#  contrast estimate     SE df t.ratio p.value
#  A2 - B1    0.4809 0.0493 98  9.760  <.0001 
#  A2 - C3    0.4952 0.0493 98 10.050  <.0001 
#  B1 - C3    0.0143 0.0493 98  0.290  0.7724 
# 
# Condition = Chasing vs. Leaving (Replication):
#  contrast estimate     SE df t.ratio p.value
#  A2 - B1    0.3516 0.0493 98  7.135  <.0001 
#  A2 - C3    0.4032 0.0493 98  8.182  <.0001 
#  B1 - C3    0.0516 0.0493 98  1.047  0.2976 

```

```{r Summary}

summary(e2RE.0)

# Linear mixed model fit by REML. t-tests use Satterthwaite's method ['lmerModLmerTest']
# Formula: Data ~ Phase * Condition + (1 | ID)
#    Data: TimeSpent_LogRatio
# Control: lmerControl(optimizer = "optimx", calc.derivs = FALSE, optCtrl = list(method = "nlminb",  
#     starttests = FALSE, kkt = FALSE))
# 
# REML criterion at convergence: -154
# 
# Scaled residuals: 
#     Min      1Q  Median      3Q     Max 
# -2.7867 -0.5127 -0.0396  0.6174  3.8114 
# 
# Random effects:
#  Groups   Name        Variance  Std.Dev.
#  ID       (Intercept) 0.0004095 0.02024 
#  Residual             0.0097137 0.09856 
# Number of obs: 120, groups:  ID, 8
# 
# Fixed effects:
#                                                     Estimate Std. Error        df t value Pr(>|t|)    
# (Intercept)                                         -0.03238    0.03557 102.64833  -0.910  0.36487    
# PhaseB1                                              0.02783    0.04928  98.00000   0.565  0.57349    
# PhaseC3                                              0.01092    0.04928  98.00000   0.222  0.82510    
# ConditionChasing vs. Flipped                         0.33058    0.04928  98.00000   6.708 1.28e-09 ***
# ConditionChasing vs. Independent                     0.18299    0.04928  98.00000   3.713  0.00034 ***
# ConditionChasing vs. Leaving                         0.51906    0.04928  98.00000  10.533  < 2e-16 ***
# ConditionChasing vs. Leaving (Replication)           0.42079    0.04928  98.00000   8.539 1.77e-13 ***
# PhaseB1:ConditionChasing vs. Flipped                -0.31515    0.06969  98.00000  -4.522 1.72e-05 ***
# PhaseC3:ConditionChasing vs. Flipped                -0.31300    0.06969  98.00000  -4.491 1.94e-05 ***
# PhaseB1:ConditionChasing vs. Independent            -0.20357    0.06969  98.00000  -2.921  0.00433 ** 
# PhaseC3:ConditionChasing vs. Independent            -0.14597    0.06969  98.00000  -2.095  0.03879 *  
# PhaseB1:ConditionChasing vs. Leaving                -0.50878    0.06969  98.00000  -7.301 7.63e-11 ***
# PhaseC3:ConditionChasing vs. Leaving                -0.50616    0.06969  98.00000  -7.263 9.14e-11 ***
# PhaseB1:ConditionChasing vs. Leaving (Replication)  -0.37945    0.06969  98.00000  -5.445 3.84e-07 ***
# PhaseC3:ConditionChasing vs. Leaving (Replication)  -0.41414    0.06969  98.00000  -5.943 4.30e-08 ***

```